### ISSUE TITLE
Not sure about toString function - a bug?

### ISSUE THREAD

**Issue by hgoebl** [justaprogrammer/ObjectId.js#1]
I didn't try / test it, but only by reading the code one thing sounds a bit strange to me:

```
ObjectId.prototype.toString = function () {
    var timestamp = this.timestamp.toString(16);
    var machine = this.machine.toString(16);
    var pid = this.pid.toString(16);
    var increment = this.increment.toString(16);
    return '00000000'.substr(0, 6 - timestamp.length) + timestamp +
           '000000'.substr(0, 6 - machine.length) + machine +
           '0000'.substr(0, 4 - pid.length) + pid +
           '000000'.substr(0, 6 - increment.length) + increment;
}
```

The zero-mask for the timestamp is 8 characters long, the substr function has 6 - timestamp.length.
The lenght of the zero-masks for machine, pid and increment are consistent with the argument for substr.

Is this a bug or have I missed something?

**Comment by zippy1981** [comment]
It might be a bug or it might be some weirdness since JavaScript usises time in miliseconds and the objectid uses seconds since unix epoch. I'll run some tests later. Just saw this bug. Are you using this code anywhere?

**Comment by hgoebl** [comment]
I'm not using it yet. Sorry, I wanted to test it, too, but haven't found time for it.

**Comment by huysentruitw** [comment]
I see this has been fixed, so why is the issue still open? :)

**Comment by zippy1981** [comment]
Good point. closed now!
